# Generated by Django 2.0 on 2018-04-17 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beamy',
            old_name='id_version',
            new_name='version',
        ),
        migrations.RenameField(
            model_name='beamyuser',
            old_name='id_beamy',
            new_name='beamy',
        ),
        migrations.RenameField(
            model_name='beamyuser',
            old_name='id_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='deviceuser',
            old_name='id_device',
            new_name='device',
        ),
        migrations.RenameField(
            model_name='deviceuser',
            old_name='id_user',
            new_name='user',
        ),
    ]
