# Generated by Django 2.0 on 2018-04-17 14:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20180417_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceuser',
            name='token',
            field=models.CharField(default=uuid.uuid4, max_length=42),
        ),
    ]
