# Generated by Django 2.0 on 2018-04-17 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_deviceuser_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='imei',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(default='device', max_length=42),
        ),
    ]
