# Generated by Django 2.0 on 2018-04-17 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20180417_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='imei',
            field=models.CharField(max_length=42),
        ),
    ]
