# Generated by Django 2.0 on 2018-03-28 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileimage',
            name='GPS',
            field=models.CharField(default=None, max_length=42),
        ),
        migrations.AlterField(
            model_name='fileimage',
            name='date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='fileimage',
            name='filesize',
            field=models.PositiveIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='fileimage',
            name='form',
            field=models.CharField(default=None, max_length=42),
        ),
        migrations.AlterField(
            model_name='fileimage',
            name='resolution',
            field=models.PositiveIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='filesong',
            name='filesize',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='filesong',
            name='resolution',
            field=models.IntegerField(blank=True),
        ),
    ]
