# Generated by Django 2.0 on 2018-03-28 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_auto_20180328_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileimage',
            name='filesize',
            field=models.PositiveIntegerField(default=''),
        ),
    ]
