# Generated by Django 2.0 on 2018-03-28 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_auto_20180328_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileimage',
            name='GPS',
            field=models.CharField(blank=True, max_length=42),
        ),
        migrations.AlterField(
            model_name='fileimage',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 28, 16, 19, 7, 22318)),
        ),
        migrations.AlterField(
            model_name='fileimage',
            name='form',
            field=models.CharField(blank=True, max_length=42),
        ),
        migrations.AlterField(
            model_name='filesong',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 28, 16, 19, 7, 22318)),
        ),
        migrations.AlterField(
            model_name='filesong',
            name='filesize',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='filesong',
            name='length',
            field=models.DurationField(default=0),
        ),
        migrations.AlterField(
            model_name='filesong',
            name='resolution',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='filevideo',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 28, 16, 19, 7, 22318)),
        ),
        migrations.AlterField(
            model_name='filevideo',
            name='filesize',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='filevideo',
            name='length',
            field=models.DurationField(default=0),
        ),
        migrations.AlterField(
            model_name='filevideo',
            name='resolution',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
