# Generated by Django 2.0 on 2018-03-28 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0007_auto_20180328_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileimage',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 28, 16, 19, 54, 905433)),
        ),
        migrations.AlterField(
            model_name='filesong',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 28, 16, 19, 54, 905433)),
        ),
        migrations.AlterField(
            model_name='filevideo',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 28, 16, 19, 54, 905433)),
        ),
    ]
