# Generated by Django 2.0 on 2018-03-28 14:32

from django.db import migrations, models
import storage.models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0008_auto_20180328_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileimage',
            name='date',
            field=models.DateTimeField(default=storage.models.now),
        ),
        migrations.AlterField(
            model_name='filesong',
            name='date',
            field=models.DateTimeField(default=storage.models.now),
        ),
        migrations.AlterField(
            model_name='filevideo',
            name='date',
            field=models.DateTimeField(default=storage.models.now),
        ),
    ]
