# Generated by Django 2.0 on 2018-03-28 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BDD', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.CharField(default='true', max_length=42)),
                ('running', models.CharField(default='false', max_length=42)),
                ('day', models.CharField(default='monday', max_length=42)),
                ('hour', models.IntegerField(default=0)),
                ('minute', models.IntegerField(default=0)),
                ('id_beamy', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='BDD.Beamy')),
            ],
            options={
                'db_table': 'alarm_alarm',
            },
        ),
    ]
