# Generated by Django 2.0 on 2018-04-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='day',
            field=models.CharField(default='monday', max_length=100),
        ),
    ]
