# Generated by Django 2.0 on 2018-04-10 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0002_auto_20180410_1538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alarm',
            old_name='id_beamy',
            new_name='beamy',
        ),
    ]
