# Generated by Django 2.0 on 2018-04-12 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0003_auto_20180410_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='name',
            field=models.CharField(default='alarm', max_length=42),
        ),
    ]
