# Generated by Django 2.0 on 2018-03-27 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Beamy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=42)),
                ('id_version', models.CharField(max_length=42)),
                ('pin', models.BigIntegerField()),
            ],
            options={
                'db_table': 'bdd_beamy',
            },
        ),
        migrations.CreateModel(
            name='BeamyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('right', models.CharField(max_length=42)),
                ('id_beamy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BDD.Beamy')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bdd_beamyuser',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=42)),
                ('imei', models.BigIntegerField()),
            ],
            options={
                'db_table': 'bdd_device',
            },
        ),
        migrations.CreateModel(
            name='DeviceUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BDD.Device')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bdd_deviceuser',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=42)),
            ],
            options={
                'db_table': 'bdd_file',
            },
        ),
        migrations.CreateModel(
            name='FileUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('right', models.CharField(max_length=42)),
                ('id_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BDD.File')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bdd_fileuser',
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=42)),
            ],
            options={
                'db_table': 'bdd_settings',
            },
        ),
    ]
