# Generated by Django 2.0 on 2018-03-23 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.CharField(default='true', max_length=42)),
                ('running', models.CharField(default='false', max_length=42)),
                ('day', models.CharField(default='monday', max_length=42)),
                ('hour', models.IntegerField(default=0)),
                ('minute', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Beamy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=42)),
                ('id_version', models.CharField(max_length=42)),
                ('pin', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Beamy_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('right', models.CharField(max_length=42)),
                ('id_beamy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BDD.Beamy')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=42)),
                ('imei', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Devices_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BDD.Device')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=42)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Files_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('right', models.CharField(max_length=42)),
                ('id_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BDD.File')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=42)),
            ],
        ),
        migrations.AddField(
            model_name='alarm',
            name='id_beamy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='BDD.Beamy'),
        ),
    ]
