# Generated by Django 2.0 on 2018-03-23 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BDD', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Files_User',
            new_name='BeamyUser',
        ),
        migrations.RenameModel(
            old_name='Devices_User',
            new_name='DeviceUser',
        ),
        migrations.RenameModel(
            old_name='Beamy_User',
            new_name='FileUser',
        ),
        migrations.RemoveField(
            model_name='beamyuser',
            name='id_file',
        ),
        migrations.RemoveField(
            model_name='fileuser',
            name='id_beamy',
        ),
        migrations.AddField(
            model_name='beamyuser',
            name='id_beamy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='BDD.Beamy'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fileuser',
            name='id_file',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='BDD.File'),
            preserve_default=False,
        ),
    ]
