# Generated by Django 2.0 on 2018-02-17 18:11

import builtins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BDD', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('state', models.CharField(max_length=42)),
                ('delay', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Beamy_Alarm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_alarm', models.ForeignKey(on_delete=builtins.callable, to='BDD.Alarm')),
                ('id_beamy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BDD.Beamy')),
            ],
        ),
    ]
