# Generated by Django 2.0 on 2018-03-23 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BDD', '0002_auto_20180323_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='id_user',
        ),
    ]
