# Generated by Django 2.0 on 2018-02-17 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BDD', '0002_alarm_beamy_alarm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beamy_alarm',
            name='id_alarm',
        ),
        migrations.RemoveField(
            model_name='beamy_alarm',
            name='id_beamy',
        ),
        migrations.AddField(
            model_name='alarm',
            name='id_beamy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='BDD.Beamy'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alarm',
            name='due_date',
            field=models.DateTimeField(),
        ),
        migrations.DeleteModel(
            name='Beamy_Alarm',
        ),
    ]
