# Generated by Django 2.0 on 2018-02-17 19:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('BDD', '0003_auto_20180217_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='delay',
            field=models.DurationField(default=datetime.timedelta(0, 300)),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 17, 20, 49, 43, 976587, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='state',
            field=models.CharField(default='set', max_length=42),
        ),
    ]
