# Generated by Django 2.0 on 2018-02-17 20:21

import BDD.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BDD', '0004_auto_20180217_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='due_date',
            field=models.DateTimeField(default=BDD.models.now_plus_1_hour),
        ),
    ]
