# Generated by Django 2.0 on 2018-02-28 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BDD', '0005_auto_20180217_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alarm',
            name='due_date',
        ),
    ]
