# Generated by Django 2.0 on 2018-02-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BDD', '0006_remove_alarm_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='day',
            field=models.CharField(default='lundi', max_length=42),
        ),
        migrations.AddField(
            model_name='alarm',
            name='hour',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='alarm',
            name='minute',
            field=models.IntegerField(default=0),
        ),
    ]
